// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycagmjylqgvocgxuhbyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYWdtanlscWd2b2NneHVoYnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDIzNDEsImV4cCI6MjA2NTExODM0MX0.TT-Jg1uPX3ihtsjhLsMlJ7-1XeBU6jkahxdM0WnuL3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);